import defaultMdxComponents from 'fumadocs-ui/mdx';
import { Accordion, Accordions } from 'fumadocs-ui/components/accordion';
import * as FilesComponents from 'fumadocs-ui/components/files';
import { ImageZoom } from 'fumadocs-ui/components/image-zoom';
import { Step, Steps } from 'fumadocs-ui/components/steps';
import * as TabsComponents from 'fumadocs-ui/components/tabs';
import type { MDXComponents } from 'mdx/types';
import type { ComponentProps } from 'react';
import { ComponentPreview } from './component-preview';
import { DocsCodeBlock } from './docs-code-block';
import {
  AccordionShowcase,
  AlertDialogShowcase,
  ButtonShowcase,
  CalendarShowcase,
  CheckboxShowcase,
  ComboBoxShowcase,
  ContextMenuShowcase,
  DateFieldShowcase,
  DatePickerShowcase,
  DateRangePickerShowcase,
  DialogShowcase,
  DisclosureShowcase,
  DropdownMenuShowcase,
  FlexShowcase,
  GridShowcase,
  InputShowcase,
  ListBoxShowcase,
  MenuShowcase,
  PanelShowcase,
  PopoverShowcase,
  ProgressBarShowcase,
  RadioGroupShowcase,
  RangeCalendarShowcase,
  ScrollAreaShowcase,
  SelectShowcase,
  SliderShowcase,
  SurfaceShowcase,
  SwitchShowcase,
  TableShowcase,
  TabsShowcase,
  TextareaShowcase,
  TimeFieldShowcase,
  TooltipShowcase,
  ToolbarShowcase,
  TreeShowcase,
  WindowShowcase,
} from './showcase/examples';
import {
  UIProvider,
  Button,
  Calendar,
  Checkbox,
  ComboBox,
  DateField,
  DatePicker,
  DateRangePicker,
  Flex,
  Grid,
  Input,
  ListBox,
  Panel,
  ProgressBar,
  RadioGroup,
  RangeCalendar,
  ScrollArea,
  Select,
  Slider,
  Surface,
  Switch,
  Table,
  Textarea,
  TimeField,
  Toolbar,
  Tree,
  Window,
} from './react-ui';

export function getMDXComponents(components?: MDXComponents) {
  return {
    ...defaultMdxComponents,
    ...FilesComponents,
    ...TabsComponents,
    Accordion,
    AccordionShowcase,
    AlertDialogShowcase,
    Accordions,
    UIProvider,
    Button,
    ButtonShowcase,
    Calendar,
    CalendarShowcase,
    Checkbox,
    CheckboxShowcase,
    ComboBox,
    ComboBoxShowcase,
    DateField,
    DateFieldShowcase,
    DatePicker,
    DatePickerShowcase,
    DateRangePicker,
    DateRangePickerShowcase,
    ComponentPreview,
    ContextMenuShowcase,
    DisclosureShowcase,
    DialogShowcase,
    DropdownMenuShowcase,
    Flex,
    FlexShowcase,
    Grid,
    GridShowcase,
    Input,
    InputShowcase,
    ListBox,
    ListBoxShowcase,
    MenuShowcase,
    Panel,
    PanelShowcase,
    PopoverShowcase,
    ProgressBar,
    ProgressBarShowcase,
    RadioGroup,
    RadioGroupShowcase,
    RangeCalendar,
    RangeCalendarShowcase,
    ScrollArea,
    ScrollAreaShowcase,
    Select,
    SelectShowcase,
    Slider,
    SliderShowcase,
    Step,
    Steps,
    Surface,
    SurfaceShowcase,
    Switch,
    SwitchShowcase,
    Table,
    TableShowcase,
    TabsShowcase,
    Textarea,
    TextareaShowcase,
    TimeField,
    TimeFieldShowcase,
    TooltipShowcase,
    Toolbar,
    ToolbarShowcase,
    Tree,
    TreeShowcase,
    Window,
    WindowShowcase,
    pre: DocsCodeBlock,
    img: (props) => (
      <ImageZoom {...(props as ComponentProps<typeof ImageZoom>)} />
    ),
    ...components,
  } satisfies MDXComponents;
}

export const useMDXComponents = getMDXComponents;

declare global {
  type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
